### ISSUE TITLE
Request compatibility with Xcode 7

### ISSUE THREAD

**Issue by soundspectrum** [x2on/libgcrypt-for-ios#12]
Hello!

Firstly, many thanks for you work Felix!

You'll probably start getting this request more (along with seeing it in your own projects), but compatibility with Xcode's "enable bitcode" would be a big step forward.  This would remove the need to build for specific architectures, ant it would also simplify the build process.

I'm happy to help to look into this, but it's rather daunting since I"m rather inexperienced in this area.  My area is realtime computing and graphics.   If there's anything I can offer or contribute to further this, I am happy to step in (though I wish my background was more applicable!).  Worse, until the project I'm working on ships (2-3 months), I'm stretched thin.  :(

Regardless, thanks again for work!

Drew

**Comment by x2on** [comment]
Fixed in current `master`

**Comment by soundspectrum** [comment]
Hi Felix, 

So these edits do address Xcode 7.1 compatibility which is helpful, but it looks like the invocation to libtool in build-libgcrypt.sh causes errors.  It's rather strange that you're not SEEING this if you're compiling under OS X.  I'm using the 7.1 toolchain under 10.10.    What do you think?

**Comment by x2on** [comment]
Hi,

It works fine here and on my CI environment.
Could you please post some details?

Best
